### ISSUE TITLE
Improve Evzen adventures

### ISSUE THREAD

**Issue by petrkucerak** [petrkucerak/diecezko.cz#52]
The game is in MVP stadium but needs some improvements.

## Tasks

- [x] closing event after submit score
- [ ] improve collision detection
- [x] change game speeds
- [x] make food larger
- [x] add stars for raising a score
- [ ] add trees to ground
- [ ] add Tomas Hoffmann in the car driving around us
- [x] make the cathedral more focused

**Comment by petrkucerak** [comment]
The game is completed to the MVP version.
